// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using declaracionPatrimonial.Data;

#nullable disable

namespace declaracionPatrimonial.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("declaracionPatrimonial.Models.Banco", b =>
                {
                    b.Property<int>("IDBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDBanco"));

                    b.Property<string>("Nombre_Banco")
                        .HasColumnType("longtext");

                    b.HasKey("IDBanco");

                    b.ToTable("Banco");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.Bienes", b =>
                {
                    b.Property<int>("IDBienes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDBienes"));

                    b.Property<string>("Descripcion_Bien")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Fecha_adquisicionBien")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Forma_adquisicionBien")
                        .HasColumnType("longtext");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IDtipoInmueble")
                        .HasColumnType("int");

                    b.Property<int?>("IDtipoPropiedad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Bienes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Precio_Bien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IDBienes");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("IDtipoInmueble");

                    b.HasIndex("IDtipoPropiedad");

                    b.ToTable("Bienes");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Apellido_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Contrasena_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Usuario")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol_Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.creditoBancario", b =>
                {
                    b.Property<int>("IDCreditoBancario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCreditoBancario"));

                    b.Property<decimal>("Cantidad_AprobadaCredito")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IDBanco")
                        .HasColumnType("int");

                    b.Property<int>("IDCuentaBancaria")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IDtipoCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Motivo_creditoBancario")
                        .HasColumnType("longtext");

                    b.HasKey("IDCreditoBancario");

                    b.HasIndex("IDBanco");

                    b.HasIndex("IDCuentaBancaria");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("IDtipoCuenta");

                    b.ToTable("creditoBancario");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.cuentaBancaria", b =>
                {
                    b.Property<int>("IDCuentaBancaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCuentaBancaria"));

                    b.Property<int>("IDBanco")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IDtipoCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Numero_cuentaBancaria")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Saldo_cuentaBancaria")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IDCuentaBancaria");

                    b.HasIndex("IDBanco");

                    b.HasIndex("IDUsuario");

                    b.HasIndex("IDtipoCuenta");

                    b.ToTable("cuentaBancaria");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.otroPasivo", b =>
                {
                    b.Property<int>("IDPasivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDPasivo"));

                    b.Property<decimal>("Cantidad_aprobadaPasivo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IDCuentaBancaria")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo_Pasivo")
                        .HasColumnType("longtext");

                    b.HasKey("IDPasivo");

                    b.HasIndex("IDCuentaBancaria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("otroPasivo");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoCuenta", b =>
                {
                    b.Property<int>("IDtipoCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDtipoCuenta"));

                    b.Property<string>("Nombre_tipoCuenta")
                        .HasColumnType("longtext");

                    b.HasKey("IDtipoCuenta");

                    b.ToTable("tipoCuenta");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoInmueble", b =>
                {
                    b.Property<int>("IDtipoInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDtipoInmueble"));

                    b.Property<string>("Nombre_tipoInmueble")
                        .HasColumnType("longtext");

                    b.HasKey("IDtipoInmueble");

                    b.ToTable("tipoInmueble");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoPropiedad", b =>
                {
                    b.Property<int>("IDtipoPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDtipoPropiedad"));

                    b.Property<string>("Nombre_tipoPropiedad")
                        .HasColumnType("longtext");

                    b.HasKey("IDtipoPropiedad");

                    b.ToTable("tipoPropiedad");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.Bienes", b =>
                {
                    b.HasOne("declaracionPatrimonial.Models.Usuario", "Usuario")
                        .WithMany("Bienes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.tipoInmueble", "tipoInmueble")
                        .WithMany("Bienes")
                        .HasForeignKey("IDtipoInmueble")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("declaracionPatrimonial.Models.tipoPropiedad", "tipoPropiedad")
                        .WithMany("Bienes")
                        .HasForeignKey("IDtipoPropiedad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");

                    b.Navigation("tipoInmueble");

                    b.Navigation("tipoPropiedad");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.creditoBancario", b =>
                {
                    b.HasOne("declaracionPatrimonial.Models.Banco", "Banco")
                        .WithMany("creditoBancario")
                        .HasForeignKey("IDBanco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.cuentaBancaria", "cuentaBancaria")
                        .WithMany("creditoBancario")
                        .HasForeignKey("IDCuentaBancaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.Usuario", "Usuario")
                        .WithMany("creditoBancario")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.tipoCuenta", "tipoCuenta")
                        .WithMany("creditoBancario")
                        .HasForeignKey("IDtipoCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("Usuario");

                    b.Navigation("cuentaBancaria");

                    b.Navigation("tipoCuenta");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.cuentaBancaria", b =>
                {
                    b.HasOne("declaracionPatrimonial.Models.Banco", "Banco")
                        .WithMany("cuentasBancaria")
                        .HasForeignKey("IDBanco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.Usuario", "Usuario")
                        .WithMany("cuentasBancaria")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.tipoCuenta", "TipoCuenta")
                        .WithMany("cuentasBancaria")
                        .HasForeignKey("IDtipoCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Banco");

                    b.Navigation("TipoCuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.otroPasivo", b =>
                {
                    b.HasOne("declaracionPatrimonial.Models.cuentaBancaria", "cuentaBancaria")
                        .WithMany("otroPasivo")
                        .HasForeignKey("IDCuentaBancaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("declaracionPatrimonial.Models.Usuario", "Usuario")
                        .WithMany("otroPasivo")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("cuentaBancaria");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.Banco", b =>
                {
                    b.Navigation("creditoBancario");

                    b.Navigation("cuentasBancaria");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.Usuario", b =>
                {
                    b.Navigation("Bienes");

                    b.Navigation("creditoBancario");

                    b.Navigation("cuentasBancaria");

                    b.Navigation("otroPasivo");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.cuentaBancaria", b =>
                {
                    b.Navigation("creditoBancario");

                    b.Navigation("otroPasivo");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoCuenta", b =>
                {
                    b.Navigation("creditoBancario");

                    b.Navigation("cuentasBancaria");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoInmueble", b =>
                {
                    b.Navigation("Bienes");
                });

            modelBuilder.Entity("declaracionPatrimonial.Models.tipoPropiedad", b =>
                {
                    b.Navigation("Bienes");
                });
#pragma warning restore 612, 618
        }
    }
}
